"use client"

import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog"
import { AgentChart } from "@/components/agent-chart"
import { BarChart3, Lightbulb, Info } from "lucide-react"

interface ChartData {
  id: string
  type: "line" | "bar" | "pie" | "area" | "scatter"
  title: string
  data: {
    data: any[]
    xAxisKey?: string
    yAxisKey?: string
  }
  justification?: string
}

interface AgentResponse {
  analysis: string
  chart?: ChartData
  success: boolean
  userQuery?: string
}

interface AgentResponseModalProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  response: AgentResponse | null
}

export function AgentResponseModal({ open, onOpenChange, response }: AgentResponseModalProps) {
  if (!response) return null

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-5xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogDescription>
            Your question:
          </DialogDescription>
          <DialogTitle className="text-2xl font-bold">
            {response.userQuery && (
              <>{response.userQuery}</>
          )}
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-6 p-6">

          {response.chart ? (
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              {/* Chart Section */}
              <div className="space-y-4">
                <div className="flex items-center gap-2 text-base font-semibold">
                  <BarChart3 className="h-8 w-8 text-white bg-primary p-1 rounded-md" />
                  <span className="text-white">{response.chart.title}</span>
                </div>
                
                <div className="rounded-lg border border-border bg-card p-4">
                  <AgentChart
                    type={response.chart.type}
                    title={response.chart.title}
                    data={response.chart.data}
                  />

                  {/* Chart Justification inside the card */}
                  {response.chart.justification && (
                    <div className="mt-4 rounded-lg border border-border/50 bg-muted/20 p-3">
                      <div className="flex items-start gap-2">
                        <Info className="h-4 w-4 text-white flex-shrink-0 mt-0.5" />
                        <div className="flex-1">
                          <div className="text-xs font-medium text-white mb-1">
                            Why This Chart?
                          </div>
                          <div className="text-xs text-muted-foreground/80 leading-relaxed">
                            {response.chart.justification}
                          </div>
                        </div>
                      </div>
                    </div>
                  )}
                </div>
              </div>

              {/* Analysis Section with justification below */}
              <div className="space-y-3">
                <div className="flex items-center gap-2 text-base font-semibold">
                  <Lightbulb className="h-8 w-8 text-white bg-primary p-1 rounded-md" />
                  <span>Detailed Analysis</span>
                </div>
                
                <div className="rounded-lg p-4">
                  <div className="text-sm text-card-foreground leading-relaxed whitespace-pre-wrap leading-relaxed font-extralight">
                    {response.analysis}
                  </div>
                </div>
              </div>
            </div>
          ) : (
            <div className="space-y-3">
               <div className="flex items-center gap-2 text-base font-semibold">
                  <Lightbulb className="h-8 w-8 text-white bg-primary p-1 rounded-md" />
                  <span>Detailed Analysis</span>
                </div>
                
                <div className="rounded-lg p-4">
                  <div className="text-sm text-card-foreground leading-relaxed whitespace-pre-wrap leading-relaxed font-extralight">
                    {response.analysis}
                  </div>
                </div>
            </div>
          )}

          {/* Disclaimer */}
          <div className="rounded-lg border border-muted bg-muted/30 p-3">
            <p className="text-xs text-muted-foreground text-center">
              This analysis is generated by AI and should be used as a guide. Please consult with a financial advisor for personalized advice.
            </p>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  )
}
